baseURL = 'https://fotkaholic.eu/'
languageCode = 'en-us'
title = 'Fotkaholic Portfolio'

[params]
cdn_url = 'https://img.fotkaholic.eu/'
use_cdn = true

[module]
[[module.imports]]
path = "github.com/nicokaiser/hugo-theme-gallery/v4"
