baseURL = 'https://fotkaholic.eu/'
languageCode = 'en-us'
title = 'Fotkaholic'
copyright = "Â© 2026 Anna Gordenko and Petr Trifanov. All rights reserved."

[params]
cdn_url = 'https://img.fotkaholic.eu/'
use_cdn = true
[params.socialIcons]
telegram = "https://t.me/fotkaholic"
instagram = "https://www.instagram.com/aru_kotsuno"


[module]
[[module.imports]]
path = "github.com/nicokaiser/hugo-theme-gallery/v4"
